### ISSUE TITLE
I'm not sure why we would want to use the values from table B.2 and limit the security strength to 2^-100. The values in table B.1 are calculated to match the security strength of the generated key.

### ISSUE THREAD

**Issue by osamahassani05355881581** [openssl/openssl-book#6]
I'm not sure why we would want to use the values from table B.2 and limit the security strength to 2^-100. The values in table B.1 are calculated to match the security strength of the generated key.

We have a copy of the function from C.1 documented at BN_prime_checks_for_size(), that return the same values as table B.1:
k:   140, security: 113 bits  (t: 38, M: 4)
k:   170, security: 129 bits  (t: 41, M: 4)
k:   200, security: 144 bits  (t: 44, M: 4)

_Originally posted by @kroeckx in https://github.com/openssl/openssl/pull/19579#discussion_r1024350075_

**Comment by osamahassani05355881581** [comment]
> ```
>     I'm not sure why we would want to use the values from table B.2 and limit the security strength to 2^-100. The values in table B.1 are calculated to match the security strength of the generated key.
> ```
> 
> 
>      
>   
> 
> We have a copy of the function from C.1 documented at BN_prime_checks_for_size(), that return the same values as table B.1:
> k:   140, security: 113 bits  (t: 38, M: 4)
> k:   170, security: 129 bits  (t: 41, M: 4)
> k:   200, security: 144 bits  (t: 44, M: 4)
> 
> 
> _Originally posted by @kroeckx in [openssl/openssl#19579 (comment)](https://github.com/openssl/openssl/pull/19579#discussion_r1024350075)_

**Comment by slontis** [comment]
What is the relevance of this issue in a PR that is in progress?

**Comment by t8m** [comment]
This is IMO just spam
